### ISSUE TITLE
I2P mirroring

### ISSUE THREAD

**Issue by DonaldTsang** [neochaner/neochan#1]
Might be really useful for those who want faster/secure connection.
Also some people just don't trust TOR

**Comment by neochaner** [comment]
Support i2p added. 
Mirror address - http://gwyok475mafdp6nnsnlo6j7so2dbfj5cpv7defh7yc76dsurq7uq.b32.i2p
AddressBook - http://stats.i2p/cgi-bin/jump.cgi?a=neochan.i2p

- Added i2p flag (for board where country flags is enabled)
- Changed default reload page timer for i2p - 30sec

**Comment by DonaldTsang** [comment]
@neochaner thanks.
